# Fantoms font build configuration

# We point to the TTF that lives in the repo root.
# ".." means: go up one folder from /sources to the top level.
sources:
  - ../Fantoms-Regular.ttf

familyName: "Fantoms"

buildOTF: false
